### PR TITLE
Adding a bower file

### PR DESCRIPTION
**Pull request by rafgeekee**
I have created this bower file for easier dependency management and adding to the bower registry.
simply run the following command to add to registry 

```
bower register freetile git://github.com/yconst/Freetile.git
```

After this, anyone can install the library using the following command,
```
bower install freetile
```

it will also be advised to create a git release for version 0.3.1.

Thanks,

PS: I've used this library on numerous projects and would like to thank you again for your hard work. I hope this addition will bring awareness to the library and provide valuable contributions from others.

### CODE REVIEW

**Comment by yconst** [comment]
Thanks a lot for this. I'll try to create a release as soon as I find some time.

**Comment by zbycz** [comment]
Sorry, i have accidentaly registered the bower package with the command metioned in first post. So now it waits only for the git release.

**Comment by rafgeekee** [comment]
i don't understand the issue, I've done a ```bower install freetile``` and have been given the master branch. That seems right to me as you have no releases.

**Comment by zbycz** [comment]
yes, it works correctly. But the author was supposed to do this, not me.

**Comment by rafgeekee** [comment]
Thats fine, i have a feeling it was already registered.

Just for your info: 
You only need to be the author to unregister the package. Anybody can register any publicly accessible repo.

The only thing still missing here is semver style release tags and versions. Once we have these, Bower users can pull specific releases instead of master if needed.

**Comment by yconst** [comment]
Created release 0.5.0.

**Pull request merged**
